// eslint-disable-next-line no-unused-expressions
export const apidata = [
  {
    trainName: "Cuttack Exp",
    trainNumber: "2346",
    departureTime: { Hours: 12, Minutes: 3, Seconds: 0 },
    seatsAvailable: { sleeper: 10, AC: 1 },
    price: { sleeper: 4072, AC: 5123 },
    delayedBy: 6,
  },
  {
    trainName: "Cochin Exp",
    trainNumber: "2348",
    departureTime: { Hours: 15, Minutes: 55, Seconds: 0 },
    seatsAvailable: { sleeper: 1, AC: 0 },
    price: { sleeper: 2, AC: 4 },
    delayedBy: 11,
  },
  {
    trainName: "Hyderabad Exp",
    trainNumber: "2341",
    departureTime: { Hours: 23, Minutes: 55, Seconds: 0 },
    seatsAvailable: { sleeper: 6, AC: 7 },
    price: { sleeper: 554, AC: 1854 },
    delayedBy: 5,
  },
  {
    trainName: "Panjim Exp",
    trainNumber: "2349",
    departureTime: { Hours: 13, Minutes: 32, Seconds: 0 },
    seatsAvailable: { sleeper: 2, AC: 1 },
    price: { sleeper: 1, AC: 2 },
    delayedBy: 9,
  },
  {
    trainName: "Srinagar Exp",
    trainNumber: "2349",
    departureTime: { Hours: 14, Minutes: 55, Seconds: 0 },
    seatsAvailable: { sleeper: 1, AC: 0 },
    price: { sleeper: 5617, AC: 5704 },
    delayedBy: 10,
  },
  {
    trainName: "Kolkata Exp",
    trainNumber: "2345",
    departureTime: { Hours: 20, Minutes: 15, Seconds: 0 },
    seatsAvailable: { sleeper: 16, AC: 70 },
    price: { sleeper: 5120, AC: 5220 },
    delayedBy: 14,
  },
  {
    trainName: "Chennai Exp",
    trainNumber: "2344",
    departureTime: { Hours: 21, Minutes: 35, Seconds: 0 },
    seatsAvailable: { sleeper: 3, AC: 1 },
    price: { sleeper: 2, AC: 5 },
    delayedBy: 15,
  },
  {
    trainName: "Mumbai Exp",
    trainNumber: "2343",
    departureTime: { Hours: 22, Minutes: 37, Seconds: 0 },
    seatsAvailable: { sleeper: 8, AC: 15 },
    price: { sleeper: 5100, AC: 5200 },
    delayedBy: 16,
  },
  {
    trainName: "Mysore Exp",
    trainNumber: "2347",
    departureTime: { Hours: 13, Minutes: 32, Seconds: 0 },
    seatsAvailable: { sleeper: 2, AC: 2 },
    price: { sleeper: 5480, AC: 5613 },
    delayedBy: 8,
  },
  {
    trainName: "Sikkim Exp",
    trainNumber: "2345",
    departureTime: { Hours: 11, Minutes: 23, Seconds: 0 },
    seatsAvailable: { sleeper: 4, AC: 4 },
    price: { sleeper: 6, AC: 2 },
    delayedBy: 5,
  },
  {
    trainName: "Bokaro Exp",
    trainNumber: "2347",
    departureTime: { Hours: 13, Minutes: 32, Seconds: 0 },
    seatsAvailable: { sleeper: 55, AC: 0 },
    price: { sleeper: 13, AC: 8 },
    delayedBy: 7,
  },
  {
    trainName: "Amritsar Exp",
    trainNumber: "2346",
    departureTime: { Hours: 19, Minutes: 0, Seconds: 0 },
    seatsAvailable: { sleeper: 15, AC: 10 },
    price: { sleeper: 15, AC: 5 },
    delayedBy: 13,
  },
  {
    trainName: "Jodhpur Exp",
    trainNumber: "2344",
    departureTime: { Hours: 11, Minutes: 0, Seconds: 0 },
    seatsAvailable: { sleeper: 33, AC: 13 },
    price: { sleeper: 5463, AC: 5574 },
    delayedBy: 4,
  },
  {
    trainName: "Lucknow Exp",
    trainNumber: "2347",
    departureTime: { Hours: 17, Minutes: 33, Seconds: 0 },
    seatsAvailable: { sleeper: 5, AC: 1 },
    price: { sleeper: 4038, AC: 5103 },
    delayedBy: 12,
  },
  {
    trainName: "Pune Exp",
    trainNumber: "2342",
    departureTime: { Hours: 23, Minutes: 0, Seconds: 0 },
    seatsAvailable: { sleeper: 6, AC: 7 },
    price: { sleeper: 14, AC: 9 },
    delayedBy: 17,
  },
];
